# -*- coding: utf-8 -*-
"""python_basics_leelakrishnaalahari.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14VXH1n9GejJUo8lCCSOIk_wE_UerPE1A
"""

# Task 1: Variables and Data Types
name = "Leela Krishna"
age = 25
height = 1.75
is_student = True

# Print all values in a single print() statement
print(name, age, height, is_student)

# Task 2: String Formatting
print(f"Name: {name} | Age: {age} | Height: {height} | Student: {is_student}")

# Task 3: Arithmetic Operations
age_in_months = age * 12
age_in_days = age * 365
remainder = age % 7
age_square = age ** 2

print("Age in months:", age_in_months)
print("Age in days:", age_in_days)
print("Remainder when age is divided by 7:", remainder)
print("Age squared:", age_square)