# -*- coding: utf-8 -*-
"""therater_ticket.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LGFfDxlUd6B1BHn7xM2Hu-NMs-BHYxC1
"""

# Theatre Booking System

TOTAL_SEATS = 350
remaining_seats = TOTAL_SEATS

total_bookings = 0
tickets_sold = 0
rejected_bookings = 0

while remaining_seats > 0:
    tickets = int(input("Enter number of tickets (0 to exit): "))

    # Exit condition
    if tickets == 0:
        break

    # Validate ticket count
    if tickets < 1 or tickets > 15:
        print("INVALID INPUT - You can book between 1 to 15 tickets only")
        continue

    # Check seat availability
    if tickets > remaining_seats:
        print("BOOKING REJECTED - Not enough seats available")
        rejected_bookings += 1
        continue

    ages = []
    invalid_age_found = False

    # Collect ages
    for i in range(tickets):
        age = int(input(f"Enter age of person {i+1}: "))

        # Age restriction check
        if age < 12:
            invalid_age_found = True
            # continue used here (though not strictly needed, included per requirement)
            continue

        ages.append(age)

    # If any invalid age → reject booking
    if invalid_age_found:
        print("BOOKING REJECTED - Age restriction")
        rejected_bookings += 1
        continue

    # Booking success
    print(f"BOOKING CONFIRMED - {tickets} tickets")
    total_bookings += 1
    tickets_sold += tickets
    remaining_seats -= tickets

    # Stop if full
    if remaining_seats == 0:
        print("THEATRE FULL")
        break

# Final Report
print("\n--- FINAL REPORT ---")
print("Total Bookings:", total_bookings)
print("Total Tickets Sold:", tickets_sold)
print("Rejected Bookings:", rejected_bookings)
print("Remaining Seats:", remaining_seats)